// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.10.0
// source: usi.proto

package usi

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Option_Type int32

const (
	Option_CHECK    Option_Type = 0
	Option_SPIN     Option_Type = 1
	Option_COMBO    Option_Type = 2
	Option_BUTTON   Option_Type = 3
	Option_STRING   Option_Type = 4
	Option_FILENAME Option_Type = 5
)

// Enum value maps for Option_Type.
var (
	Option_Type_name = map[int32]string{
		0: "CHECK",
		1: "SPIN",
		2: "COMBO",
		3: "BUTTON",
		4: "STRING",
		5: "FILENAME",
	}
	Option_Type_value = map[string]int32{
		"CHECK":    0,
		"SPIN":     1,
		"COMBO":    2,
		"BUTTON":   3,
		"STRING":   4,
		"FILENAME": 5,
	}
)

func (x Option_Type) Enum() *Option_Type {
	p := new(Option_Type)
	*p = x
	return p
}

func (x Option_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Option_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_usi_proto_enumTypes[0].Descriptor()
}

func (Option_Type) Type() protoreflect.EnumType {
	return &file_usi_proto_enumTypes[0]
}

func (x Option_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Option_Type.Descriptor instead.
func (Option_Type) EnumDescriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{0, 0}
}

type GameOverRequest_Result int32

const (
	GameOverRequest_WIN  GameOverRequest_Result = 0
	GameOverRequest_LOSE GameOverRequest_Result = 1
	GameOverRequest_DRAW GameOverRequest_Result = 2
)

// Enum value maps for GameOverRequest_Result.
var (
	GameOverRequest_Result_name = map[int32]string{
		0: "WIN",
		1: "LOSE",
		2: "DRAW",
	}
	GameOverRequest_Result_value = map[string]int32{
		"WIN":  0,
		"LOSE": 1,
		"DRAW": 2,
	}
)

func (x GameOverRequest_Result) Enum() *GameOverRequest_Result {
	p := new(GameOverRequest_Result)
	*p = x
	return p
}

func (x GameOverRequest_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameOverRequest_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_usi_proto_enumTypes[1].Descriptor()
}

func (GameOverRequest_Result) Type() protoreflect.EnumType {
	return &file_usi_proto_enumTypes[1]
}

func (x GameOverRequest_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameOverRequest_Result.Descriptor instead.
func (GameOverRequest_Result) EnumDescriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{20, 0}
}

type Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type            Option_Type   `protobuf:"varint,2,opt,name=type,proto3,enum=usi.Option_Type" json:"type,omitempty"`
	Check           *Option_Check `protobuf:"bytes,3,opt,name=check,proto3" json:"check,omitempty"`
	Spin            *Option_Spin  `protobuf:"bytes,4,opt,name=spin,proto3" json:"spin,omitempty"`
	Combo           *Option_Combo `protobuf:"bytes,5,opt,name=combo,proto3" json:"combo,omitempty"`
	StringDefault   string        `protobuf:"bytes,6,opt,name=string_default,json=stringDefault,proto3" json:"string_default,omitempty"`
	FilenameDefault string        `protobuf:"bytes,7,opt,name=filename_default,json=filenameDefault,proto3" json:"filename_default,omitempty"`
}

func (x *Option) Reset() {
	*x = Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{0}
}

func (x *Option) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Option) GetType() Option_Type {
	if x != nil {
		return x.Type
	}
	return Option_CHECK
}

func (x *Option) GetCheck() *Option_Check {
	if x != nil {
		return x.Check
	}
	return nil
}

func (x *Option) GetSpin() *Option_Spin {
	if x != nil {
		return x.Spin
	}
	return nil
}

func (x *Option) GetCombo() *Option_Combo {
	if x != nil {
		return x.Combo
	}
	return nil
}

func (x *Option) GetStringDefault() string {
	if x != nil {
		return x.StringDefault
	}
	return ""
}

func (x *Option) GetFilenameDefault() string {
	if x != nil {
		return x.FilenameDefault
	}
	return ""
}

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sfen  string   `protobuf:"bytes,1,opt,name=sfen,proto3" json:"sfen,omitempty"` // If sfen is empty string, it will be interpreted as `startpos`.
	Moves []string `protobuf:"bytes,2,rep,name=moves,proto3" json:"moves,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetSfen() string {
	if x != nil {
		return x.Sfen
	}
	return ""
}

func (x *Position) GetMoves() []string {
	if x != nil {
		return x.Moves
	}
	return nil
}

type FirstUSIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FirstUSIRequest) Reset() {
	*x = FirstUSIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FirstUSIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirstUSIRequest) ProtoMessage() {}

func (x *FirstUSIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirstUSIRequest.ProtoReflect.Descriptor instead.
func (*FirstUSIRequest) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{2}
}

type FirstUSIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author  string    `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Options []*Option `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *FirstUSIResponse) Reset() {
	*x = FirstUSIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FirstUSIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirstUSIResponse) ProtoMessage() {}

func (x *FirstUSIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirstUSIResponse.ProtoReflect.Descriptor instead.
func (*FirstUSIResponse) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{3}
}

func (x *FirstUSIResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FirstUSIResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *FirstUSIResponse) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

type IsReadyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IsReadyRequest) Reset() {
	*x = IsReadyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReadyRequest) ProtoMessage() {}

func (x *IsReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReadyRequest.ProtoReflect.Descriptor instead.
func (*IsReadyRequest) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{4}
}

type IsReadyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsReady bool `protobuf:"varint,1,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
}

func (x *IsReadyResponse) Reset() {
	*x = IsReadyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReadyResponse) ProtoMessage() {}

func (x *IsReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReadyResponse.ProtoReflect.Descriptor instead.
func (*IsReadyResponse) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{5}
}

func (x *IsReadyResponse) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type SetOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetOptionRequest) Reset() {
	*x = SetOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOptionRequest) ProtoMessage() {}

func (x *SetOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOptionRequest.ProtoReflect.Descriptor instead.
func (*SetOptionRequest) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{6}
}

func (x *SetOptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetOptionRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Option *Option `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
}

func (x *SetOptionResponse) Reset() {
	*x = SetOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOptionResponse) ProtoMessage() {}

func (x *SetOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOptionResponse.ProtoReflect.Descriptor instead.
func (*SetOptionResponse) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{7}
}

func (x *SetOptionResponse) GetOption() *Option {
	if x != nil {
		return x.Option
	}
	return nil
}

type NewGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewGameRequest) Reset() {
	*x = NewGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGameRequest) ProtoMessage() {}

func (x *NewGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGameRequest.ProtoReflect.Descriptor instead.
func (*NewGameRequest) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{8}
}

type NewGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewGameResponse) Reset() {
	*x = NewGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGameResponse) ProtoMessage() {}

func (x *NewGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGameResponse.ProtoReflect.Descriptor instead.
func (*NewGameResponse) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{9}
}

type SetPositionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *SetPositionRequest) Reset() {
	*x = SetPositionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPositionRequest) ProtoMessage() {}

func (x *SetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPositionRequest.ProtoReflect.Descriptor instead.
func (*SetPositionRequest) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{10}
}

func (x *SetPositionRequest) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type SetPositionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetPositionResponse) Reset() {
	*x = SetPositionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPositionResponse) ProtoMessage() {}

func (x *SetPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPositionResponse.ProtoReflect.Descriptor instead.
func (*SetPositionResponse) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{11}
}

type GoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsPonder bool  `protobuf:"varint,1,opt,name=is_ponder,json=isPonder,proto3" json:"is_ponder,omitempty"` // 先読み
	Btime    int32 `protobuf:"varint,2,opt,name=btime,proto3" json:"btime,omitempty"`                       // 先手の残り時間[ms]
	Wtime    int32 `protobuf:"varint,3,opt,name=wtime,proto3" json:"wtime,omitempty"`                       // 後手の残り時間[ms]
	Byoyomi  int32 `protobuf:"varint,4,opt,name=byoyomi,proto3" json:"byoyomi,omitempty"`                   // 秒読み[ms]
	// フィッシャークロックルールの加算時間
	Binc     int32           `protobuf:"varint,5,opt,name=binc,proto3" json:"binc,omitempty"`         // 先手の加算時間[ms]
	Winc     int32           `protobuf:"varint,6,opt,name=winc,proto3" json:"winc,omitempty"`         // 後手の加算時間[ms]
	Infinite bool            `protobuf:"varint,7,opt,name=infinite,proto3" json:"infinite,omitempty"` // 時間無制限で思考させる
	Mate     *GoRequest_Mate `protobuf:"bytes,8,opt,name=mate,proto3" json:"mate,omitempty"`
}

func (x *GoRequest) Reset() {
	*x = GoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoRequest) ProtoMessage() {}

func (x *GoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoRequest.ProtoReflect.Descriptor instead.
func (*GoRequest) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{12}
}

func (x *GoRequest) GetIsPonder() bool {
	if x != nil {
		return x.IsPonder
	}
	return false
}

func (x *GoRequest) GetBtime() int32 {
	if x != nil {
		return x.Btime
	}
	return 0
}

func (x *GoRequest) GetWtime() int32 {
	if x != nil {
		return x.Wtime
	}
	return 0
}

func (x *GoRequest) GetByoyomi() int32 {
	if x != nil {
		return x.Byoyomi
	}
	return 0
}

func (x *GoRequest) GetBinc() int32 {
	if x != nil {
		return x.Binc
	}
	return 0
}

func (x *GoRequest) GetWinc() int32 {
	if x != nil {
		return x.Winc
	}
	return 0
}

func (x *GoRequest) GetInfinite() bool {
	if x != nil {
		return x.Infinite
	}
	return false
}

func (x *GoRequest) GetMate() *GoRequest_Mate {
	if x != nil {
		return x.Mate
	}
	return nil
}

type GoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GoResponse) Reset() {
	*x = GoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoResponse) ProtoMessage() {}

func (x *GoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoResponse.ProtoReflect.Descriptor instead.
func (*GoResponse) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{13}
}

type StopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{14}
}

type StopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BestMove   string `protobuf:"bytes,1,opt,name=best_move,json=bestMove,proto3" json:"best_move,omitempty"`       // その時点での指し手
	PonderMove string `protobuf:"bytes,2,opt,name=ponder_move,json=ponderMove,proto3" json:"ponder_move,omitempty"` // 次の相手の指し手を予想したもの. go
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{15}
}

func (x *StopResponse) GetBestMove() string {
	if x != nil {
		return x.BestMove
	}
	return ""
}

func (x *StopResponse) GetPonderMove() string {
	if x != nil {
		return x.PonderMove
	}
	return ""
}

// Ponderhit は、go ponder による先読み中に、相手の指し手が StopResponse.ponder_move と
// 一致している場合にクライアントから送る。 先読みから通常思考に切り替える。
type PonderhitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PonderhitRequest) Reset() {
	*x = PonderhitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PonderhitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PonderhitRequest) ProtoMessage() {}

func (x *PonderhitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PonderhitRequest.ProtoReflect.Descriptor instead.
func (*PonderhitRequest) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{16}
}

type PonderhitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PonderhitResponse) Reset() {
	*x = PonderhitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PonderhitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PonderhitResponse) ProtoMessage() {}

func (x *PonderhitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PonderhitResponse.ProtoReflect.Descriptor instead.
func (*PonderhitResponse) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{17}
}

type QuitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuitRequest) Reset() {
	*x = QuitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitRequest) ProtoMessage() {}

func (x *QuitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitRequest.ProtoReflect.Descriptor instead.
func (*QuitRequest) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{18}
}

type QuitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuitResponse) Reset() {
	*x = QuitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitResponse) ProtoMessage() {}

func (x *QuitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitResponse.ProtoReflect.Descriptor instead.
func (*QuitResponse) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{19}
}

type GameOverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result GameOverRequest_Result `protobuf:"varint,1,opt,name=result,proto3,enum=usi.GameOverRequest_Result" json:"result,omitempty"`
}

func (x *GameOverRequest) Reset() {
	*x = GameOverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameOverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOverRequest) ProtoMessage() {}

func (x *GameOverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOverRequest.ProtoReflect.Descriptor instead.
func (*GameOverRequest) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{20}
}

func (x *GameOverRequest) GetResult() GameOverRequest_Result {
	if x != nil {
		return x.Result
	}
	return GameOverRequest_WIN
}

type GameOverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameOverResponse) Reset() {
	*x = GameOverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameOverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOverResponse) ProtoMessage() {}

func (x *GameOverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOverResponse.ProtoReflect.Descriptor instead.
func (*GameOverResponse) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{21}
}

type Option_Check struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default bool `protobuf:"varint,1,opt,name=default,proto3" json:"default,omitempty"`
}

func (x *Option_Check) Reset() {
	*x = Option_Check{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Option_Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option_Check) ProtoMessage() {}

func (x *Option_Check) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option_Check.ProtoReflect.Descriptor instead.
func (*Option_Check) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Option_Check) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

type Option_Spin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default int32 `protobuf:"varint,1,opt,name=default,proto3" json:"default,omitempty"`
	Min     int32 `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max     int32 `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *Option_Spin) Reset() {
	*x = Option_Spin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Option_Spin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option_Spin) ProtoMessage() {}

func (x *Option_Spin) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option_Spin.ProtoReflect.Descriptor instead.
func (*Option_Spin) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Option_Spin) GetDefault() int32 {
	if x != nil {
		return x.Default
	}
	return 0
}

func (x *Option_Spin) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Option_Spin) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Option_Combo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default string   `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Vars    []string `protobuf:"bytes,2,rep,name=vars,proto3" json:"vars,omitempty"`
}

func (x *Option_Combo) Reset() {
	*x = Option_Combo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Option_Combo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option_Combo) ProtoMessage() {}

func (x *Option_Combo) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option_Combo.ProtoReflect.Descriptor instead.
func (*Option_Combo) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Option_Combo) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *Option_Combo) GetVars() []string {
	if x != nil {
		return x.Vars
	}
	return nil
}

type GoRequest_Mate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infinite     bool  `protobuf:"varint,1,opt,name=infinite,proto3" json:"infinite,omitempty"`
	ThinkingTime int32 `protobuf:"varint,2,opt,name=thinking_time,json=thinkingTime,proto3" json:"thinking_time,omitempty"`
}

func (x *GoRequest_Mate) Reset() {
	*x = GoRequest_Mate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usi_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoRequest_Mate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoRequest_Mate) ProtoMessage() {}

func (x *GoRequest_Mate) ProtoReflect() protoreflect.Message {
	mi := &file_usi_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoRequest_Mate.ProtoReflect.Descriptor instead.
func (*GoRequest_Mate) Descriptor() ([]byte, []int) {
	return file_usi_proto_rawDescGZIP(), []int{12, 0}
}

func (x *GoRequest_Mate) GetInfinite() bool {
	if x != nil {
		return x.Infinite
	}
	return false
}

func (x *GoRequest_Mate) GetThinkingTime() int32 {
	if x != nil {
		return x.ThinkingTime
	}
	return 0
}

var File_usi_proto protoreflect.FileDescriptor

var file_usi_proto_rawDesc = []byte{
	0x0a, 0x09, 0x75, 0x73, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x75, 0x73, 0x69,
	0x22, 0xfa, 0x03, 0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x75, 0x73, 0x69, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x73, 0x69, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x24,
	0x0a, 0x04, 0x73, 0x70, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75,
	0x73, 0x69, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x70, 0x69, 0x6e, 0x52, 0x04,
	0x73, 0x70, 0x69, 0x6e, 0x12, 0x27, 0x0a, 0x05, 0x63, 0x6f, 0x6d, 0x62, 0x6f, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x73, 0x69, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x6f, 0x52, 0x05, 0x63, 0x6f, 0x6d, 0x62, 0x6f, 0x12, 0x25, 0x0a,
	0x0e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x1a,
	0x21, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x1a, 0x44, 0x0a, 0x04, 0x53, 0x70, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x1a, 0x35, 0x0a, 0x05, 0x43, 0x6f, 0x6d, 0x62,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x76,
	0x61, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x72, 0x73, 0x22,
	0x4c, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x48, 0x45, 0x43, 0x4b,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x50, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x43, 0x4f, 0x4d, 0x42, 0x4f, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x55, 0x54, 0x54, 0x4f,
	0x4e, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x12,
	0x0c, 0x0a, 0x08, 0x46, 0x49, 0x4c, 0x45, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x05, 0x22, 0x34, 0x0a,
	0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x66, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x66, 0x65, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f,
	0x76, 0x65, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x46, 0x69, 0x72, 0x73, 0x74, 0x55, 0x53, 0x49, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x65, 0x0a, 0x10, 0x46, 0x69, 0x72, 0x73, 0x74, 0x55,
	0x53, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x25, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x73, 0x69, 0x2e, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x10, 0x0a,
	0x0e, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x2c, 0x0a, 0x0f, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x22, 0x38, 0x0a,
	0x10, 0x53, 0x65, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x38, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x06,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75,
	0x73, 0x69, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x10, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3f, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x75, 0x73, 0x69, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xa4,
	0x02, 0x0a, 0x09, 0x47, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x73, 0x5f, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x50, 0x6f, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x62, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x77, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x77, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x79, 0x6f, 0x79, 0x6f, 0x6d, 0x69,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x79, 0x6f, 0x79, 0x6f, 0x6d, 0x69, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x69, 0x6e, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x62,
	0x69, 0x6e, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x69, 0x6e, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x77, 0x69, 0x6e, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x6e, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x6d, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x75, 0x73, 0x69, 0x2e, 0x47, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x4d, 0x61, 0x74, 0x65, 0x52, 0x04, 0x6d, 0x61, 0x74, 0x65, 0x1a, 0x47, 0x0a, 0x04,
	0x4d, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x6e, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x74, 0x68, 0x69, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x68, 0x69, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x47, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x4c, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65,
	0x22, 0x12, 0x0a, 0x10, 0x50, 0x6f, 0x6e, 0x64, 0x65, 0x72, 0x68, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x50, 0x6f, 0x6e, 0x64, 0x65, 0x72, 0x68, 0x69,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x51, 0x75, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x51, 0x75, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6d, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65,
	0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x75, 0x73,
	0x69, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x25, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x49,
	0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x44, 0x52, 0x41, 0x57, 0x10, 0x02, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x61, 0x6d, 0x65, 0x4f,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x3b, 0x75, 0x73, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_usi_proto_rawDescOnce sync.Once
	file_usi_proto_rawDescData = file_usi_proto_rawDesc
)

func file_usi_proto_rawDescGZIP() []byte {
	file_usi_proto_rawDescOnce.Do(func() {
		file_usi_proto_rawDescData = protoimpl.X.CompressGZIP(file_usi_proto_rawDescData)
	})
	return file_usi_proto_rawDescData
}

var file_usi_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_usi_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_usi_proto_goTypes = []interface{}{
	(Option_Type)(0),            // 0: usi.Option.Type
	(GameOverRequest_Result)(0), // 1: usi.GameOverRequest.Result
	(*Option)(nil),              // 2: usi.Option
	(*Position)(nil),            // 3: usi.Position
	(*FirstUSIRequest)(nil),     // 4: usi.FirstUSIRequest
	(*FirstUSIResponse)(nil),    // 5: usi.FirstUSIResponse
	(*IsReadyRequest)(nil),      // 6: usi.IsReadyRequest
	(*IsReadyResponse)(nil),     // 7: usi.IsReadyResponse
	(*SetOptionRequest)(nil),    // 8: usi.SetOptionRequest
	(*SetOptionResponse)(nil),   // 9: usi.SetOptionResponse
	(*NewGameRequest)(nil),      // 10: usi.NewGameRequest
	(*NewGameResponse)(nil),     // 11: usi.NewGameResponse
	(*SetPositionRequest)(nil),  // 12: usi.SetPositionRequest
	(*SetPositionResponse)(nil), // 13: usi.SetPositionResponse
	(*GoRequest)(nil),           // 14: usi.GoRequest
	(*GoResponse)(nil),          // 15: usi.GoResponse
	(*StopRequest)(nil),         // 16: usi.StopRequest
	(*StopResponse)(nil),        // 17: usi.StopResponse
	(*PonderhitRequest)(nil),    // 18: usi.PonderhitRequest
	(*PonderhitResponse)(nil),   // 19: usi.PonderhitResponse
	(*QuitRequest)(nil),         // 20: usi.QuitRequest
	(*QuitResponse)(nil),        // 21: usi.QuitResponse
	(*GameOverRequest)(nil),     // 22: usi.GameOverRequest
	(*GameOverResponse)(nil),    // 23: usi.GameOverResponse
	(*Option_Check)(nil),        // 24: usi.Option.Check
	(*Option_Spin)(nil),         // 25: usi.Option.Spin
	(*Option_Combo)(nil),        // 26: usi.Option.Combo
	(*GoRequest_Mate)(nil),      // 27: usi.GoRequest.Mate
}
var file_usi_proto_depIdxs = []int32{
	0,  // 0: usi.Option.type:type_name -> usi.Option.Type
	24, // 1: usi.Option.check:type_name -> usi.Option.Check
	25, // 2: usi.Option.spin:type_name -> usi.Option.Spin
	26, // 3: usi.Option.combo:type_name -> usi.Option.Combo
	2,  // 4: usi.FirstUSIResponse.options:type_name -> usi.Option
	2,  // 5: usi.SetOptionResponse.option:type_name -> usi.Option
	3,  // 6: usi.SetPositionRequest.position:type_name -> usi.Position
	27, // 7: usi.GoRequest.mate:type_name -> usi.GoRequest.Mate
	1,  // 8: usi.GameOverRequest.result:type_name -> usi.GameOverRequest.Result
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_usi_proto_init() }
func file_usi_proto_init() {
	if File_usi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_usi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FirstUSIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FirstUSIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsReadyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsReadyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPositionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPositionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PonderhitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PonderhitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameOverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameOverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Option_Check); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Option_Spin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Option_Combo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usi_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoRequest_Mate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_usi_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_usi_proto_goTypes,
		DependencyIndexes: file_usi_proto_depIdxs,
		EnumInfos:         file_usi_proto_enumTypes,
		MessageInfos:      file_usi_proto_msgTypes,
	}.Build()
	File_usi_proto = out.File
	file_usi_proto_rawDesc = nil
	file_usi_proto_goTypes = nil
	file_usi_proto_depIdxs = nil
}
