// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usi.proto

package usi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Option_Type int32

const (
	Option_CHECK    Option_Type = 0
	Option_SPIN     Option_Type = 1
	Option_COMBO    Option_Type = 2
	Option_BUTTON   Option_Type = 3
	Option_STRING   Option_Type = 4
	Option_FILENAME Option_Type = 5
)

var Option_Type_name = map[int32]string{
	0: "CHECK",
	1: "SPIN",
	2: "COMBO",
	3: "BUTTON",
	4: "STRING",
	5: "FILENAME",
}

var Option_Type_value = map[string]int32{
	"CHECK":    0,
	"SPIN":     1,
	"COMBO":    2,
	"BUTTON":   3,
	"STRING":   4,
	"FILENAME": 5,
}

func (x Option_Type) String() string {
	return proto.EnumName(Option_Type_name, int32(x))
}

func (Option_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{0, 0}
}

type GameOverRequest_Result int32

const (
	GameOverRequest_WIN  GameOverRequest_Result = 0
	GameOverRequest_LOSE GameOverRequest_Result = 1
	GameOverRequest_DRAW GameOverRequest_Result = 2
)

var GameOverRequest_Result_name = map[int32]string{
	0: "WIN",
	1: "LOSE",
	2: "DRAW",
}

var GameOverRequest_Result_value = map[string]int32{
	"WIN":  0,
	"LOSE": 1,
	"DRAW": 2,
}

func (x GameOverRequest_Result) String() string {
	return proto.EnumName(GameOverRequest_Result_name, int32(x))
}

func (GameOverRequest_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{20, 0}
}

type Option struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 Option_Type   `protobuf:"varint,2,opt,name=type,proto3,enum=usi.Option_Type" json:"type,omitempty"`
	Check                *Option_Check `protobuf:"bytes,3,opt,name=check,proto3" json:"check,omitempty"`
	Spin                 *Option_Spin  `protobuf:"bytes,4,opt,name=spin,proto3" json:"spin,omitempty"`
	Combo                *Option_Combo `protobuf:"bytes,5,opt,name=combo,proto3" json:"combo,omitempty"`
	StringDefault        string        `protobuf:"bytes,6,opt,name=string_default,json=stringDefault,proto3" json:"string_default,omitempty"`
	FilenameDefault      string        `protobuf:"bytes,7,opt,name=filename_default,json=filenameDefault,proto3" json:"filename_default,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Option) Reset()         { *m = Option{} }
func (m *Option) String() string { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()    {}
func (*Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{0}
}

func (m *Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option.Unmarshal(m, b)
}
func (m *Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option.Marshal(b, m, deterministic)
}
func (m *Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option.Merge(m, src)
}
func (m *Option) XXX_Size() int {
	return xxx_messageInfo_Option.Size(m)
}
func (m *Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Option proto.InternalMessageInfo

func (m *Option) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Option) GetType() Option_Type {
	if m != nil {
		return m.Type
	}
	return Option_CHECK
}

func (m *Option) GetCheck() *Option_Check {
	if m != nil {
		return m.Check
	}
	return nil
}

func (m *Option) GetSpin() *Option_Spin {
	if m != nil {
		return m.Spin
	}
	return nil
}

func (m *Option) GetCombo() *Option_Combo {
	if m != nil {
		return m.Combo
	}
	return nil
}

func (m *Option) GetStringDefault() string {
	if m != nil {
		return m.StringDefault
	}
	return ""
}

func (m *Option) GetFilenameDefault() string {
	if m != nil {
		return m.FilenameDefault
	}
	return ""
}

type Option_Check struct {
	Default              bool     `protobuf:"varint,1,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Option_Check) Reset()         { *m = Option_Check{} }
func (m *Option_Check) String() string { return proto.CompactTextString(m) }
func (*Option_Check) ProtoMessage()    {}
func (*Option_Check) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{0, 0}
}

func (m *Option_Check) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option_Check.Unmarshal(m, b)
}
func (m *Option_Check) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option_Check.Marshal(b, m, deterministic)
}
func (m *Option_Check) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option_Check.Merge(m, src)
}
func (m *Option_Check) XXX_Size() int {
	return xxx_messageInfo_Option_Check.Size(m)
}
func (m *Option_Check) XXX_DiscardUnknown() {
	xxx_messageInfo_Option_Check.DiscardUnknown(m)
}

var xxx_messageInfo_Option_Check proto.InternalMessageInfo

func (m *Option_Check) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

type Option_Spin struct {
	Default              int32    `protobuf:"varint,1,opt,name=default,proto3" json:"default,omitempty"`
	Min                  int32    `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int32    `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Option_Spin) Reset()         { *m = Option_Spin{} }
func (m *Option_Spin) String() string { return proto.CompactTextString(m) }
func (*Option_Spin) ProtoMessage()    {}
func (*Option_Spin) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{0, 1}
}

func (m *Option_Spin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option_Spin.Unmarshal(m, b)
}
func (m *Option_Spin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option_Spin.Marshal(b, m, deterministic)
}
func (m *Option_Spin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option_Spin.Merge(m, src)
}
func (m *Option_Spin) XXX_Size() int {
	return xxx_messageInfo_Option_Spin.Size(m)
}
func (m *Option_Spin) XXX_DiscardUnknown() {
	xxx_messageInfo_Option_Spin.DiscardUnknown(m)
}

var xxx_messageInfo_Option_Spin proto.InternalMessageInfo

func (m *Option_Spin) GetDefault() int32 {
	if m != nil {
		return m.Default
	}
	return 0
}

func (m *Option_Spin) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Option_Spin) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

type Option_Combo struct {
	Default              string   `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Vars                 []string `protobuf:"bytes,2,rep,name=vars,proto3" json:"vars,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Option_Combo) Reset()         { *m = Option_Combo{} }
func (m *Option_Combo) String() string { return proto.CompactTextString(m) }
func (*Option_Combo) ProtoMessage()    {}
func (*Option_Combo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{0, 2}
}

func (m *Option_Combo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option_Combo.Unmarshal(m, b)
}
func (m *Option_Combo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option_Combo.Marshal(b, m, deterministic)
}
func (m *Option_Combo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option_Combo.Merge(m, src)
}
func (m *Option_Combo) XXX_Size() int {
	return xxx_messageInfo_Option_Combo.Size(m)
}
func (m *Option_Combo) XXX_DiscardUnknown() {
	xxx_messageInfo_Option_Combo.DiscardUnknown(m)
}

var xxx_messageInfo_Option_Combo proto.InternalMessageInfo

func (m *Option_Combo) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *Option_Combo) GetVars() []string {
	if m != nil {
		return m.Vars
	}
	return nil
}

type Position struct {
	Sfen                 string   `protobuf:"bytes,1,opt,name=sfen,proto3" json:"sfen,omitempty"`
	Moves                []string `protobuf:"bytes,2,rep,name=moves,proto3" json:"moves,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{1}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetSfen() string {
	if m != nil {
		return m.Sfen
	}
	return ""
}

func (m *Position) GetMoves() []string {
	if m != nil {
		return m.Moves
	}
	return nil
}

type FirstUSIRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirstUSIRequest) Reset()         { *m = FirstUSIRequest{} }
func (m *FirstUSIRequest) String() string { return proto.CompactTextString(m) }
func (*FirstUSIRequest) ProtoMessage()    {}
func (*FirstUSIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{2}
}

func (m *FirstUSIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirstUSIRequest.Unmarshal(m, b)
}
func (m *FirstUSIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirstUSIRequest.Marshal(b, m, deterministic)
}
func (m *FirstUSIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirstUSIRequest.Merge(m, src)
}
func (m *FirstUSIRequest) XXX_Size() int {
	return xxx_messageInfo_FirstUSIRequest.Size(m)
}
func (m *FirstUSIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FirstUSIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FirstUSIRequest proto.InternalMessageInfo

type FirstUSIResponse struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author               string    `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Options              []*Option `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FirstUSIResponse) Reset()         { *m = FirstUSIResponse{} }
func (m *FirstUSIResponse) String() string { return proto.CompactTextString(m) }
func (*FirstUSIResponse) ProtoMessage()    {}
func (*FirstUSIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{3}
}

func (m *FirstUSIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirstUSIResponse.Unmarshal(m, b)
}
func (m *FirstUSIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirstUSIResponse.Marshal(b, m, deterministic)
}
func (m *FirstUSIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirstUSIResponse.Merge(m, src)
}
func (m *FirstUSIResponse) XXX_Size() int {
	return xxx_messageInfo_FirstUSIResponse.Size(m)
}
func (m *FirstUSIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FirstUSIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FirstUSIResponse proto.InternalMessageInfo

func (m *FirstUSIResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FirstUSIResponse) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *FirstUSIResponse) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

type IsReadyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsReadyRequest) Reset()         { *m = IsReadyRequest{} }
func (m *IsReadyRequest) String() string { return proto.CompactTextString(m) }
func (*IsReadyRequest) ProtoMessage()    {}
func (*IsReadyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{4}
}

func (m *IsReadyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsReadyRequest.Unmarshal(m, b)
}
func (m *IsReadyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsReadyRequest.Marshal(b, m, deterministic)
}
func (m *IsReadyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsReadyRequest.Merge(m, src)
}
func (m *IsReadyRequest) XXX_Size() int {
	return xxx_messageInfo_IsReadyRequest.Size(m)
}
func (m *IsReadyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsReadyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsReadyRequest proto.InternalMessageInfo

type IsReadyResponse struct {
	IsReady              bool     `protobuf:"varint,1,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsReadyResponse) Reset()         { *m = IsReadyResponse{} }
func (m *IsReadyResponse) String() string { return proto.CompactTextString(m) }
func (*IsReadyResponse) ProtoMessage()    {}
func (*IsReadyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{5}
}

func (m *IsReadyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsReadyResponse.Unmarshal(m, b)
}
func (m *IsReadyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsReadyResponse.Marshal(b, m, deterministic)
}
func (m *IsReadyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsReadyResponse.Merge(m, src)
}
func (m *IsReadyResponse) XXX_Size() int {
	return xxx_messageInfo_IsReadyResponse.Size(m)
}
func (m *IsReadyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsReadyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsReadyResponse proto.InternalMessageInfo

func (m *IsReadyResponse) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

type SetOptionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOptionRequest) Reset()         { *m = SetOptionRequest{} }
func (m *SetOptionRequest) String() string { return proto.CompactTextString(m) }
func (*SetOptionRequest) ProtoMessage()    {}
func (*SetOptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{6}
}

func (m *SetOptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOptionRequest.Unmarshal(m, b)
}
func (m *SetOptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOptionRequest.Marshal(b, m, deterministic)
}
func (m *SetOptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOptionRequest.Merge(m, src)
}
func (m *SetOptionRequest) XXX_Size() int {
	return xxx_messageInfo_SetOptionRequest.Size(m)
}
func (m *SetOptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetOptionRequest proto.InternalMessageInfo

func (m *SetOptionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetOptionRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SetOptionResponse struct {
	Option               *Option  `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOptionResponse) Reset()         { *m = SetOptionResponse{} }
func (m *SetOptionResponse) String() string { return proto.CompactTextString(m) }
func (*SetOptionResponse) ProtoMessage()    {}
func (*SetOptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{7}
}

func (m *SetOptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOptionResponse.Unmarshal(m, b)
}
func (m *SetOptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOptionResponse.Marshal(b, m, deterministic)
}
func (m *SetOptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOptionResponse.Merge(m, src)
}
func (m *SetOptionResponse) XXX_Size() int {
	return xxx_messageInfo_SetOptionResponse.Size(m)
}
func (m *SetOptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetOptionResponse proto.InternalMessageInfo

func (m *SetOptionResponse) GetOption() *Option {
	if m != nil {
		return m.Option
	}
	return nil
}

type NewGameRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewGameRequest) Reset()         { *m = NewGameRequest{} }
func (m *NewGameRequest) String() string { return proto.CompactTextString(m) }
func (*NewGameRequest) ProtoMessage()    {}
func (*NewGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{8}
}

func (m *NewGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewGameRequest.Unmarshal(m, b)
}
func (m *NewGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewGameRequest.Marshal(b, m, deterministic)
}
func (m *NewGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewGameRequest.Merge(m, src)
}
func (m *NewGameRequest) XXX_Size() int {
	return xxx_messageInfo_NewGameRequest.Size(m)
}
func (m *NewGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewGameRequest proto.InternalMessageInfo

type NewGameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewGameResponse) Reset()         { *m = NewGameResponse{} }
func (m *NewGameResponse) String() string { return proto.CompactTextString(m) }
func (*NewGameResponse) ProtoMessage()    {}
func (*NewGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{9}
}

func (m *NewGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewGameResponse.Unmarshal(m, b)
}
func (m *NewGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewGameResponse.Marshal(b, m, deterministic)
}
func (m *NewGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewGameResponse.Merge(m, src)
}
func (m *NewGameResponse) XXX_Size() int {
	return xxx_messageInfo_NewGameResponse.Size(m)
}
func (m *NewGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewGameResponse proto.InternalMessageInfo

type SetPositionRequest struct {
	Position             *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SetPositionRequest) Reset()         { *m = SetPositionRequest{} }
func (m *SetPositionRequest) String() string { return proto.CompactTextString(m) }
func (*SetPositionRequest) ProtoMessage()    {}
func (*SetPositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{10}
}

func (m *SetPositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPositionRequest.Unmarshal(m, b)
}
func (m *SetPositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPositionRequest.Marshal(b, m, deterministic)
}
func (m *SetPositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPositionRequest.Merge(m, src)
}
func (m *SetPositionRequest) XXX_Size() int {
	return xxx_messageInfo_SetPositionRequest.Size(m)
}
func (m *SetPositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPositionRequest proto.InternalMessageInfo

func (m *SetPositionRequest) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type SetPositionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPositionResponse) Reset()         { *m = SetPositionResponse{} }
func (m *SetPositionResponse) String() string { return proto.CompactTextString(m) }
func (*SetPositionResponse) ProtoMessage()    {}
func (*SetPositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{11}
}

func (m *SetPositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPositionResponse.Unmarshal(m, b)
}
func (m *SetPositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPositionResponse.Marshal(b, m, deterministic)
}
func (m *SetPositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPositionResponse.Merge(m, src)
}
func (m *SetPositionResponse) XXX_Size() int {
	return xxx_messageInfo_SetPositionResponse.Size(m)
}
func (m *SetPositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPositionResponse proto.InternalMessageInfo

type GoRequest struct {
	IsPonder bool  `protobuf:"varint,1,opt,name=is_ponder,json=isPonder,proto3" json:"is_ponder,omitempty"`
	Btime    int32 `protobuf:"varint,2,opt,name=btime,proto3" json:"btime,omitempty"`
	Wtime    int32 `protobuf:"varint,3,opt,name=wtime,proto3" json:"wtime,omitempty"`
	Byoyomi  int32 `protobuf:"varint,4,opt,name=byoyomi,proto3" json:"byoyomi,omitempty"`
	// フィッシャークロックルールの加算時間
	Binc                 int32           `protobuf:"varint,5,opt,name=binc,proto3" json:"binc,omitempty"`
	Winc                 int32           `protobuf:"varint,6,opt,name=winc,proto3" json:"winc,omitempty"`
	Infinite             bool            `protobuf:"varint,7,opt,name=infinite,proto3" json:"infinite,omitempty"`
	Mate                 *GoRequest_Mate `protobuf:"bytes,8,opt,name=mate,proto3" json:"mate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GoRequest) Reset()         { *m = GoRequest{} }
func (m *GoRequest) String() string { return proto.CompactTextString(m) }
func (*GoRequest) ProtoMessage()    {}
func (*GoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{12}
}

func (m *GoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoRequest.Unmarshal(m, b)
}
func (m *GoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoRequest.Marshal(b, m, deterministic)
}
func (m *GoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoRequest.Merge(m, src)
}
func (m *GoRequest) XXX_Size() int {
	return xxx_messageInfo_GoRequest.Size(m)
}
func (m *GoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoRequest proto.InternalMessageInfo

func (m *GoRequest) GetIsPonder() bool {
	if m != nil {
		return m.IsPonder
	}
	return false
}

func (m *GoRequest) GetBtime() int32 {
	if m != nil {
		return m.Btime
	}
	return 0
}

func (m *GoRequest) GetWtime() int32 {
	if m != nil {
		return m.Wtime
	}
	return 0
}

func (m *GoRequest) GetByoyomi() int32 {
	if m != nil {
		return m.Byoyomi
	}
	return 0
}

func (m *GoRequest) GetBinc() int32 {
	if m != nil {
		return m.Binc
	}
	return 0
}

func (m *GoRequest) GetWinc() int32 {
	if m != nil {
		return m.Winc
	}
	return 0
}

func (m *GoRequest) GetInfinite() bool {
	if m != nil {
		return m.Infinite
	}
	return false
}

func (m *GoRequest) GetMate() *GoRequest_Mate {
	if m != nil {
		return m.Mate
	}
	return nil
}

type GoRequest_Mate struct {
	Infinite             bool     `protobuf:"varint,1,opt,name=infinite,proto3" json:"infinite,omitempty"`
	ThinkingTime         int32    `protobuf:"varint,2,opt,name=thinking_time,json=thinkingTime,proto3" json:"thinking_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoRequest_Mate) Reset()         { *m = GoRequest_Mate{} }
func (m *GoRequest_Mate) String() string { return proto.CompactTextString(m) }
func (*GoRequest_Mate) ProtoMessage()    {}
func (*GoRequest_Mate) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{12, 0}
}

func (m *GoRequest_Mate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoRequest_Mate.Unmarshal(m, b)
}
func (m *GoRequest_Mate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoRequest_Mate.Marshal(b, m, deterministic)
}
func (m *GoRequest_Mate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoRequest_Mate.Merge(m, src)
}
func (m *GoRequest_Mate) XXX_Size() int {
	return xxx_messageInfo_GoRequest_Mate.Size(m)
}
func (m *GoRequest_Mate) XXX_DiscardUnknown() {
	xxx_messageInfo_GoRequest_Mate.DiscardUnknown(m)
}

var xxx_messageInfo_GoRequest_Mate proto.InternalMessageInfo

func (m *GoRequest_Mate) GetInfinite() bool {
	if m != nil {
		return m.Infinite
	}
	return false
}

func (m *GoRequest_Mate) GetThinkingTime() int32 {
	if m != nil {
		return m.ThinkingTime
	}
	return 0
}

type GoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoResponse) Reset()         { *m = GoResponse{} }
func (m *GoResponse) String() string { return proto.CompactTextString(m) }
func (*GoResponse) ProtoMessage()    {}
func (*GoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{13}
}

func (m *GoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoResponse.Unmarshal(m, b)
}
func (m *GoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoResponse.Marshal(b, m, deterministic)
}
func (m *GoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoResponse.Merge(m, src)
}
func (m *GoResponse) XXX_Size() int {
	return xxx_messageInfo_GoResponse.Size(m)
}
func (m *GoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoResponse proto.InternalMessageInfo

type StopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{14}
}

func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (m *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(m, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

type StopResponse struct {
	BestMove             string   `protobuf:"bytes,1,opt,name=best_move,json=bestMove,proto3" json:"best_move,omitempty"`
	PonderMove           string   `protobuf:"bytes,2,opt,name=ponder_move,json=ponderMove,proto3" json:"ponder_move,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{15}
}

func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (m *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(m, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

func (m *StopResponse) GetBestMove() string {
	if m != nil {
		return m.BestMove
	}
	return ""
}

func (m *StopResponse) GetPonderMove() string {
	if m != nil {
		return m.PonderMove
	}
	return ""
}

// Ponderhit は、go ponder による先読み中に、相手の指し手が StopResponse.ponder_move と
// 一致している場合にクライアントから送る。 先読みから通常思考に切り替える。
type PonderhitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PonderhitRequest) Reset()         { *m = PonderhitRequest{} }
func (m *PonderhitRequest) String() string { return proto.CompactTextString(m) }
func (*PonderhitRequest) ProtoMessage()    {}
func (*PonderhitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{16}
}

func (m *PonderhitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PonderhitRequest.Unmarshal(m, b)
}
func (m *PonderhitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PonderhitRequest.Marshal(b, m, deterministic)
}
func (m *PonderhitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PonderhitRequest.Merge(m, src)
}
func (m *PonderhitRequest) XXX_Size() int {
	return xxx_messageInfo_PonderhitRequest.Size(m)
}
func (m *PonderhitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PonderhitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PonderhitRequest proto.InternalMessageInfo

type PonderhitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PonderhitResponse) Reset()         { *m = PonderhitResponse{} }
func (m *PonderhitResponse) String() string { return proto.CompactTextString(m) }
func (*PonderhitResponse) ProtoMessage()    {}
func (*PonderhitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{17}
}

func (m *PonderhitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PonderhitResponse.Unmarshal(m, b)
}
func (m *PonderhitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PonderhitResponse.Marshal(b, m, deterministic)
}
func (m *PonderhitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PonderhitResponse.Merge(m, src)
}
func (m *PonderhitResponse) XXX_Size() int {
	return xxx_messageInfo_PonderhitResponse.Size(m)
}
func (m *PonderhitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PonderhitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PonderhitResponse proto.InternalMessageInfo

type QuitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitRequest) Reset()         { *m = QuitRequest{} }
func (m *QuitRequest) String() string { return proto.CompactTextString(m) }
func (*QuitRequest) ProtoMessage()    {}
func (*QuitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{18}
}

func (m *QuitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitRequest.Unmarshal(m, b)
}
func (m *QuitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitRequest.Marshal(b, m, deterministic)
}
func (m *QuitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitRequest.Merge(m, src)
}
func (m *QuitRequest) XXX_Size() int {
	return xxx_messageInfo_QuitRequest.Size(m)
}
func (m *QuitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuitRequest proto.InternalMessageInfo

type QuitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitResponse) Reset()         { *m = QuitResponse{} }
func (m *QuitResponse) String() string { return proto.CompactTextString(m) }
func (*QuitResponse) ProtoMessage()    {}
func (*QuitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{19}
}

func (m *QuitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitResponse.Unmarshal(m, b)
}
func (m *QuitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitResponse.Marshal(b, m, deterministic)
}
func (m *QuitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitResponse.Merge(m, src)
}
func (m *QuitResponse) XXX_Size() int {
	return xxx_messageInfo_QuitResponse.Size(m)
}
func (m *QuitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuitResponse proto.InternalMessageInfo

type GameOverRequest struct {
	Result               GameOverRequest_Result `protobuf:"varint,1,opt,name=result,proto3,enum=usi.GameOverRequest_Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GameOverRequest) Reset()         { *m = GameOverRequest{} }
func (m *GameOverRequest) String() string { return proto.CompactTextString(m) }
func (*GameOverRequest) ProtoMessage()    {}
func (*GameOverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{20}
}

func (m *GameOverRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameOverRequest.Unmarshal(m, b)
}
func (m *GameOverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameOverRequest.Marshal(b, m, deterministic)
}
func (m *GameOverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameOverRequest.Merge(m, src)
}
func (m *GameOverRequest) XXX_Size() int {
	return xxx_messageInfo_GameOverRequest.Size(m)
}
func (m *GameOverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameOverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameOverRequest proto.InternalMessageInfo

func (m *GameOverRequest) GetResult() GameOverRequest_Result {
	if m != nil {
		return m.Result
	}
	return GameOverRequest_WIN
}

type GameOverResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameOverResponse) Reset()         { *m = GameOverResponse{} }
func (m *GameOverResponse) String() string { return proto.CompactTextString(m) }
func (*GameOverResponse) ProtoMessage()    {}
func (*GameOverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9581fce32fc54607, []int{21}
}

func (m *GameOverResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameOverResponse.Unmarshal(m, b)
}
func (m *GameOverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameOverResponse.Marshal(b, m, deterministic)
}
func (m *GameOverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameOverResponse.Merge(m, src)
}
func (m *GameOverResponse) XXX_Size() int {
	return xxx_messageInfo_GameOverResponse.Size(m)
}
func (m *GameOverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameOverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameOverResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("usi.Option_Type", Option_Type_name, Option_Type_value)
	proto.RegisterEnum("usi.GameOverRequest_Result", GameOverRequest_Result_name, GameOverRequest_Result_value)
	proto.RegisterType((*Option)(nil), "usi.Option")
	proto.RegisterType((*Option_Check)(nil), "usi.Option.Check")
	proto.RegisterType((*Option_Spin)(nil), "usi.Option.Spin")
	proto.RegisterType((*Option_Combo)(nil), "usi.Option.Combo")
	proto.RegisterType((*Position)(nil), "usi.Position")
	proto.RegisterType((*FirstUSIRequest)(nil), "usi.FirstUSIRequest")
	proto.RegisterType((*FirstUSIResponse)(nil), "usi.FirstUSIResponse")
	proto.RegisterType((*IsReadyRequest)(nil), "usi.IsReadyRequest")
	proto.RegisterType((*IsReadyResponse)(nil), "usi.IsReadyResponse")
	proto.RegisterType((*SetOptionRequest)(nil), "usi.SetOptionRequest")
	proto.RegisterType((*SetOptionResponse)(nil), "usi.SetOptionResponse")
	proto.RegisterType((*NewGameRequest)(nil), "usi.NewGameRequest")
	proto.RegisterType((*NewGameResponse)(nil), "usi.NewGameResponse")
	proto.RegisterType((*SetPositionRequest)(nil), "usi.SetPositionRequest")
	proto.RegisterType((*SetPositionResponse)(nil), "usi.SetPositionResponse")
	proto.RegisterType((*GoRequest)(nil), "usi.GoRequest")
	proto.RegisterType((*GoRequest_Mate)(nil), "usi.GoRequest.Mate")
	proto.RegisterType((*GoResponse)(nil), "usi.GoResponse")
	proto.RegisterType((*StopRequest)(nil), "usi.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "usi.StopResponse")
	proto.RegisterType((*PonderhitRequest)(nil), "usi.PonderhitRequest")
	proto.RegisterType((*PonderhitResponse)(nil), "usi.PonderhitResponse")
	proto.RegisterType((*QuitRequest)(nil), "usi.QuitRequest")
	proto.RegisterType((*QuitResponse)(nil), "usi.QuitResponse")
	proto.RegisterType((*GameOverRequest)(nil), "usi.GameOverRequest")
	proto.RegisterType((*GameOverResponse)(nil), "usi.GameOverResponse")
}

func init() { proto.RegisterFile("usi.proto", fileDescriptor_9581fce32fc54607) }

var fileDescriptor_9581fce32fc54607 = []byte{
	// 821 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x55, 0x4d, 0x6f, 0x22, 0x47,
	0x10, 0x0d, 0xcc, 0x07, 0x43, 0x81, 0x61, 0x68, 0x27, 0xd1, 0x04, 0x1f, 0x42, 0x66, 0x63, 0xad,
	0x57, 0x8a, 0x38, 0x78, 0x13, 0x69, 0xa5, 0x1c, 0xa2, 0xf5, 0xc7, 0x3a, 0x28, 0x36, 0x38, 0x0d,
	0xab, 0x95, 0x72, 0xb1, 0x06, 0xd3, 0x8e, 0x5b, 0xeb, 0x99, 0x9e, 0x4c, 0x37, 0x78, 0xf9, 0x3f,
	0xf9, 0x95, 0x39, 0x45, 0xd5, 0x1f, 0x80, 0x2d, 0xdf, 0xaa, 0x5e, 0x3d, 0x5e, 0xbf, 0xaa, 0xea,
	0x1e, 0xa0, 0xb9, 0x94, 0x7c, 0x58, 0x56, 0x42, 0x09, 0xe2, 0x2d, 0x25, 0x4f, 0xff, 0xf3, 0x20,
	0x9c, 0x94, 0x8a, 0x8b, 0x82, 0x10, 0xf0, 0x8b, 0x2c, 0x67, 0x49, 0x6d, 0x50, 0x3b, 0x6a, 0x52,
	0x1d, 0x93, 0x1f, 0xc1, 0x57, 0xeb, 0x92, 0x25, 0xf5, 0x41, 0xed, 0xa8, 0x73, 0x1c, 0x0f, 0xf1,
	0xd7, 0x86, 0x3e, 0x9c, 0xad, 0x4b, 0x46, 0x75, 0x95, 0xbc, 0x86, 0xe0, 0xf6, 0x9e, 0xdd, 0x7e,
	0x4e, 0xbc, 0x41, 0xed, 0xa8, 0x75, 0xdc, 0xdb, 0xa5, 0x9d, 0x62, 0x81, 0x9a, 0x3a, 0xca, 0xc9,
	0x92, 0x17, 0x89, 0xaf, 0x79, 0x4f, 0xe4, 0xa6, 0x25, 0x2f, 0xa8, 0xae, 0x6a, 0x39, 0x91, 0xcf,
	0x45, 0x12, 0xbc, 0x20, 0x87, 0x05, 0x6a, 0xea, 0xe4, 0x10, 0x3a, 0x52, 0x55, 0xbc, 0xf8, 0xfb,
	0x66, 0xc1, 0xee, 0xb2, 0xe5, 0x83, 0x4a, 0x42, 0xed, 0x7d, 0xcf, 0xa0, 0x67, 0x06, 0x24, 0x6f,
	0x20, 0xbe, 0xe3, 0x0f, 0x0c, 0x1b, 0xda, 0x10, 0x1b, 0x9a, 0xd8, 0x75, 0xb8, 0xa5, 0xf6, 0x7f,
	0x80, 0x40, 0x1b, 0x26, 0x09, 0x34, 0x1c, 0x15, 0xe7, 0x11, 0x51, 0x97, 0xf6, 0xcf, 0xc0, 0x47,
	0xaf, 0xcf, 0x19, 0xc1, 0x86, 0x41, 0x62, 0xf0, 0x72, 0x5e, 0xe8, 0x99, 0x05, 0x14, 0x43, 0x8d,
	0x64, 0x5f, 0xf4, 0x78, 0x10, 0xc9, 0xbe, 0xf4, 0x7f, 0x81, 0x40, 0xb7, 0xf2, 0x5c, 0xa6, 0xb9,
	0x95, 0x21, 0xe0, 0xaf, 0xb2, 0x4a, 0x26, 0xf5, 0x81, 0x87, 0xfb, 0xc0, 0x38, 0xbd, 0x04, 0x1f,
	0xe7, 0x4e, 0x9a, 0x10, 0x9c, 0xfe, 0x7e, 0x7e, 0xfa, 0x47, 0xfc, 0x15, 0x89, 0xc0, 0x9f, 0x5e,
	0x8f, 0xc6, 0x71, 0x4d, 0x83, 0x93, 0xab, 0x93, 0x49, 0x5c, 0x27, 0x00, 0xe1, 0xc9, 0xc7, 0xd9,
	0x6c, 0x32, 0x8e, 0x3d, 0x8c, 0xa7, 0x33, 0x3a, 0x1a, 0x5f, 0xc4, 0x3e, 0x69, 0x43, 0xf4, 0x61,
	0x74, 0x79, 0x3e, 0x7e, 0x7f, 0x75, 0x1e, 0x07, 0xe9, 0xcf, 0x10, 0x5d, 0x0b, 0xc9, 0xdd, 0xf6,
	0xe5, 0x1d, 0x2b, 0xdc, 0xf6, 0x31, 0x26, 0x5f, 0x43, 0x90, 0x8b, 0x15, 0x73, 0x16, 0x4c, 0x92,
	0xf6, 0xa0, 0xfb, 0x81, 0x57, 0x52, 0x7d, 0x9c, 0x8e, 0x28, 0xfb, 0x67, 0xc9, 0xa4, 0x4a, 0x19,
	0xc4, 0x5b, 0x48, 0x96, 0xa2, 0x90, 0xec, 0xc5, 0xeb, 0xf4, 0x2d, 0x84, 0xd9, 0x52, 0xdd, 0x8b,
	0x4a, 0x0f, 0xa7, 0x49, 0x6d, 0x46, 0x0e, 0xa1, 0x21, 0xf4, 0x7e, 0x65, 0xe2, 0x0d, 0xbc, 0xa3,
	0xd6, 0x71, 0x6b, 0x67, 0xe7, 0xd4, 0xd5, 0xd2, 0x18, 0x3a, 0x23, 0x49, 0x59, 0xb6, 0x58, 0xbb,
	0x83, 0x7f, 0x82, 0xee, 0x06, 0xb1, 0xe7, 0x7e, 0x07, 0x11, 0x97, 0x37, 0x15, 0x62, 0x6e, 0x75,
	0xdc, 0x50, 0xd2, 0x77, 0x10, 0x4f, 0x99, 0xb2, 0xaa, 0x46, 0x81, 0x74, 0xa0, 0xce, 0x17, 0xd6,
	0x64, 0x9d, 0x2f, 0xb0, 0xe7, 0x55, 0xf6, 0xb0, 0x64, 0xd6, 0xa1, 0x49, 0xd2, 0x77, 0xd0, 0xdb,
	0xf9, 0xa5, 0x3d, 0xe9, 0x15, 0x84, 0xc6, 0x99, 0xfe, 0xf9, 0x33, 0xd3, 0xb6, 0x84, 0x9e, 0xc7,
	0xec, 0xf1, 0x22, 0xcb, 0x99, 0xf3, 0xdc, 0x83, 0xee, 0x06, 0x31, 0x4a, 0xe9, 0x6f, 0x40, 0xa6,
	0x4c, 0xb9, 0x5d, 0x38, 0x6b, 0x6f, 0x20, 0x2a, 0x2d, 0x64, 0x4f, 0xd8, 0xd3, 0x27, 0x6c, 0x78,
	0x9b, 0x72, 0xfa, 0x0d, 0xec, 0x3f, 0x11, 0xb0, 0xba, 0xff, 0xd6, 0xa1, 0x79, 0x21, 0x9c, 0xde,
	0x01, 0x34, 0xb9, 0xbc, 0x29, 0x45, 0xb1, 0x60, 0x95, 0x1d, 0x4d, 0xc4, 0xe5, 0xb5, 0xce, 0xb1,
	0xef, 0xb9, 0xe2, 0x39, 0xb3, 0xd7, 0xd6, 0x24, 0x88, 0x3e, 0x6a, 0xd4, 0x5c, 0x5d, 0x93, 0xe0,
	0x9d, 0x9d, 0xaf, 0xc5, 0x5a, 0xe4, 0x5c, 0xbf, 0xe4, 0x80, 0xba, 0x14, 0x97, 0x3e, 0xe7, 0xc5,
	0xad, 0x7e, 0xb9, 0x01, 0xd5, 0x31, 0x62, 0x8f, 0x88, 0x85, 0x06, 0xc3, 0x98, 0xf4, 0x21, 0xe2,
	0xc5, 0x1d, 0x2f, 0xb8, 0x62, 0xfa, 0x29, 0xa2, 0x13, 0x9b, 0x93, 0xd7, 0xe0, 0xe7, 0x99, 0x62,
	0x49, 0xa4, 0x5b, 0xde, 0xd7, 0x2d, 0x6f, 0x9a, 0x18, 0x5e, 0x65, 0x8a, 0x51, 0x4d, 0xe8, 0x5f,
	0x80, 0x8f, 0xd9, 0x13, 0xb1, 0xda, 0x33, 0xb1, 0x57, 0xb0, 0xa7, 0xee, 0x79, 0xf1, 0x19, 0x3f,
	0x12, 0x3b, 0xed, 0xb5, 0x1d, 0x38, 0xe3, 0x39, 0x4b, 0xdb, 0x00, 0x78, 0x80, 0x1d, 0xda, 0x1e,
	0xb4, 0xa6, 0x4a, 0x94, 0x6e, 0x5d, 0x97, 0xd0, 0x36, 0xa9, 0xdd, 0xfa, 0x01, 0x34, 0xe7, 0x4c,
	0xaa, 0x1b, 0x7c, 0x0c, 0xf6, 0xde, 0x44, 0x08, 0x5c, 0x89, 0x15, 0x23, 0xdf, 0x43, 0xcb, 0xcc,
	0xd7, 0x94, 0xcd, 0x1d, 0x02, 0x03, 0x21, 0x21, 0x25, 0x10, 0x9b, 0x81, 0xdf, 0x73, 0xe5, 0x4e,
	0xd8, 0x87, 0xde, 0x0e, 0xb6, 0x75, 0xf1, 0xe7, 0x72, 0xcb, 0xe9, 0x40, 0xdb, 0xa4, 0xb6, 0x9c,
	0x43, 0x17, 0x6f, 0xd0, 0x64, 0xc5, 0x2a, 0xb7, 0xde, 0xb7, 0x10, 0x56, 0x4c, 0xba, 0x0f, 0x49,
	0xe7, 0xf8, 0xc0, 0x4c, 0xee, 0x29, 0x6b, 0x48, 0x35, 0x85, 0x5a, 0x6a, 0x7a, 0x08, 0xa1, 0x41,
	0x48, 0x03, 0xbc, 0x4f, 0xa3, 0xb1, 0xf9, 0xa0, 0x5c, 0x4e, 0xa6, 0xe7, 0x71, 0x0d, 0xa3, 0x33,
	0xfa, 0xfe, 0x53, 0x5c, 0x47, 0xdb, 0x5b, 0x21, 0x63, 0xe1, 0xa4, 0xf1, 0x57, 0x30, 0xfc, 0x75,
	0x29, 0xf9, 0x3c, 0xd4, 0xff, 0x27, 0x6f, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x05, 0x2f,
	0x5f, 0x5c, 0x06, 0x00, 0x00,
}
